import React from 'react'
import Head from 'next/head'
import Link from 'next/Link'
export default function Layout({children, title}) {
  return (
   <>
   <Head>
        <title>{title ? title + '-Amazone':'Amazone'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div className='flex min-h-screen flex-col justify-between'>
    <header>
        <nav className='flex h-12 justify-between shadow-md items-center px-4'>
         <Link href="/">
         <a href="" className='text-lg font-bold'>amazona</a>
         </Link>
         <div>
             <Link href="/cart"><a href="" className='p-2'>Cart</a></Link>
             <Link href="/login"><a href="" className='p-2'>Login</a></Link>
         </div>
        </nav>
    </header>
    <main className='container m-auto mt-4 px-4'>
            {children}
    </main>
    <footer className='flex justify-center items-center h-10 shadow-inner'>
        <p>Coopiright</p>
    </footer>
   </div>
   </>
  )
}
